### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by caichunjian520** [project-dev/paperangsample#1]
When tap the connect button, the app will crash for index out of range.

It seems the app skips the scan process when execute find() function. Can you add the scan process to make it work?

And there is a key point I am confused. I worked on a lot of BLE projects. The usual way is to find the name of peripheral, then loop through the services or characteristics to get the key characteristics to read, write, or set notify. As I search on github, all repo of paperang use a very wierd UUID 00001101-0000-1000-8000-00805F9B34FB, which I don't why.

I connect the printer with lightblue app, only find 0xFF01(Notify), 0xFF02(Write) 0xFF03(Notify) which can work with. I think the app should send cmd and data packet to 0xFF02 characteristic. But the result is totally wrong. Can you make a explain why? 

Thanks.

**Comment by project-dev** [comment]
I am not good at English, so I use a translation service.
There may be sentences that are difficult to understand.

The find () method finds the paired Paperang.
Therefore, we do not implement scanning of unpaired Paperang.
I'm thinking of implementing an unpaired Paperanngu scan in due course.

I don't even know about the UUID 000011001-0000-1000-8000-00805F9B34FB.

Regarding the last question, I'm sorry, I'm lacking in knowledge and can't answer.

Thank you.

--Original translation--
英語は苦手なので、翻訳サービスを利用しています。
分かりづらい文章があるかもしれません。

find()メソッドでは、ペアリング済みのPaperangを探します。
その為、ペアリングしていないPaperangのスキャンは実装していません。
ペアリングされていないPaperannguのスキャンは、いずれ実装しようと考えています。

UUID 000011001-0000-1000-8000-00805F9B34FBについては私もわかりません。

最後の質問に関しては、ごめんなさい、今の私では知識が不足しており、回答ができません。

ありがとう。
